/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ProductoController;
import Model.ProductoModel;
import javax.swing.table.DefaultTableModel;
import java.util.List;
/**
 *
 * @author luisr
 */
public class ListarProductosView extends javax.swing.JFrame {

    /**
     * Creates new form ListarProductosView
     */
    private DefaultTableModel modeloTablaProductos;
    private List<ProductoModel> productos;
    private ProductoController productoControlador;
    
    public ListarProductosView() {
        initComponents();
        modeloTablaProductos=(DefaultTableModel)jTableProductos.getModel();
        jTableProductos.setModel(modeloTablaProductos);
        productoControlador = new ProductoController();
        productos= productoControlador.verProductos();
        crearTablaProductos(productos, modeloTablaProductos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private  void crearTablaProductos(List<ProductoModel> productosParaTabla,DefaultTableModel modeloTablaProductos){
        String []datos=new String[7];
        int i;
        //limpia la tabla antes
        for(i=0;i<modeloTablaProductos.getRowCount();i++){
            modeloTablaProductos.removeRow(i);
            i=i-1;
        }
        
        
        for(ProductoModel o : productosParaTabla){

            datos[0]=String.valueOf(o.getProducto_ID());
            datos[1]=o.getNombre();
            datos[2]=o.getMarca();
            datos[3]=o.getDescripcion();
            datos[4]=String.valueOf(o.getPrecioVenta());
            datos[5]=String.valueOf(o.getCantidadEnStock());
            datos[6]=String.valueOf(o.getCatidadMinimaEnStock());
            modeloTablaProductos.addRow(datos);
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelProductos = new javax.swing.JPanel();
        jScrollPaneProductosTabla = new javax.swing.JScrollPane();
        jTableProductos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Producto", "Marca", "Descripcion", "PrecioVenta", "Stock", "Cant.Min"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableProductos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTableProductosKeyTyped(evt);
            }
        });
        jScrollPaneProductosTabla.setViewportView(jTableProductos);

        javax.swing.GroupLayout jPanelProductosLayout = new javax.swing.GroupLayout(jPanelProductos);
        jPanelProductos.setLayout(jPanelProductosLayout);
        jPanelProductosLayout.setHorizontalGroup(
            jPanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductosLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jScrollPaneProductosTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
        );
        jPanelProductosLayout.setVerticalGroup(
            jPanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductosLayout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(jScrollPaneProductosTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(301, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jPanelProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableProductosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableProductosKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableProductosKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        ListarProductosView l= new ListarProductosView();
        l.setVisible(true);

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarProductosView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelProductos;
    private javax.swing.JScrollPane jScrollPaneProductosTabla;
    private javax.swing.JTable jTableProductos;
    // End of variables declaration//GEN-END:variables
}
