/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.EmpleadoModel;
import Model.EstadoModel;
import Model.OrdenModel;
import Model.ServicioModel;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.event.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author manuel
 */
public class ListarOrdenesDeTrabajoView extends javax.swing.JFrame {

    /**
     * Creates new form ListarOrdenesDeTrabajo
     */
    
    public ListarOrdenesDeTrabajoView() {
        this.initComponents();
        this.lookAndFeel();
        
        
        
        
    }
/*private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        
        
        
        

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                
            new Object [][] {
                {2111, "alta", "en proceso", "20/10/19", "Juan", "Mantenimiento", "ABC222", "2664000614"}

            },
            new String [] {
                "N°", "Urgencia", "Estado", "Fecha", "Emisor", "Servicio", "Patente", "Telefono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }*/// </editor-fold> 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N°", "Urgencia", "Estado", "Cajero", "Patente", "Telefono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Servicios"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mantenimiento"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 322, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(263, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    private void lookAndFeel() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarOrdenesDeTrabajoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarOrdenesDeTrabajoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarOrdenesDeTrabajoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarOrdenesDeTrabajoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        
    }
    
 
    
    
public void setModel(ArrayList<OrdenModel> rows){
    DefaultTableModel defaultTableModel;
    Iterator<OrdenModel> iterator = rows.iterator();
    
    defaultTableModel=new DefaultTableModel();
    defaultTableModel.addColumn("N°");
    defaultTableModel.addColumn("Urgencia");
    defaultTableModel.addColumn("Estado");
   /** defaultTableModel.addColumn("Fecha");**/
    defaultTableModel.addColumn( "Cajero");
    defaultTableModel.addColumn("Tel. cliente");
    defaultTableModel.addColumn("Patente");
    
    while(iterator.hasNext()){
        String[] aux = new String[7];
        OrdenModel auxOrden= new OrdenModel();
        auxOrden=iterator.next();
        aux[0]=Long.toString( auxOrden.getNro_Orden());
        aux[1]= auxOrden.getUrgencia();
        if(auxOrden.getEstado()== EstadoModel.EN_PROCESO){
            aux[2]="En proceso";
        }else{
            aux[2]="Finalizado";
        }
        aux[3]=auxOrden.getEmpleado_cajero().getNombre();
        aux[4]=auxOrden.getCliente().getTelefonos_Del_Responsable().get(0);
        aux[5]=auxOrden.getVehiculo().getPatente();
        defaultTableModel.addRow(aux); 
    }
    
    jTable1.setModel(defaultTableModel);
    
    
    jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
        public void valueChanged(ListSelectionEvent event) {
            DefaultTableModel defaultTableModel2=new DefaultTableModel();
            
            defaultTableModel2.addColumn("Servicios");
            
            System.out.println(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
            Iterator<ServicioModel> it=rows.get(jTable1.getSelectedRow()).getServicios().iterator();
            while(it.hasNext()){
                ServicioModel auxServicio=new ServicioModel();
                auxServicio= it.next();
                System.out.println(auxServicio.getNombre());
                defaultTableModel2.addRow(new Object[]{auxServicio.getNombre()});
            }
            jTable2.setModel(defaultTableModel2);
            
            
            
            DefaultTableModel defaultTableModel3=new DefaultTableModel();
            
            defaultTableModel3.addColumn("Mantenimiento");
            
            
            Iterator<EmpleadoModel> it2=rows.get(jTable1.getSelectedRow()).getEmpleados_mantenimiento().iterator();
            while(it2.hasNext()){
                EmpleadoModel auxEmpleado=new EmpleadoModel();
                auxEmpleado= it2.next();
                
                defaultTableModel3.addRow(new Object[]{auxEmpleado.getNombre()});
            }
            jTable3.setModel(defaultTableModel3);
            
            
        }
    });
    
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables
}
